apiVersion: apps/v1
kind: Deployment
metadata:
  name : mongo-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key:  mongo-mongo-root-username
        - name: MONGODB_INIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key:  mongo-mongo-root-password

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    